/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotDealsRouteImport } from './routes/hot-deals'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlashDealsRouteImport } from './routes/flash-deals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorSettingsRouteImport } from './routes/vendor/settings'
import { Route as VendorProductsRouteImport } from './routes/vendor/products'
import { Route as VendorOrdersRouteImport } from './routes/vendor/orders'
import { Route as VendorDashboardRouteImport } from './routes/vendor/dashboard'
import { Route as VendorApplicationRejectedRouteImport } from './routes/vendor/application-rejected'
import { Route as VendorApplicationPendingRouteImport } from './routes/vendor/application-pending'
import { Route as TrackOrderNumberRouteImport } from './routes/track.$orderNumber'
import { Route as ProductProductSlugRouteImport } from './routes/product.$productSlug'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as AdminVendorApplicationsRouteImport } from './routes/admin/vendor-applications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as VendorOrdersOrderIdRouteImport } from './routes/vendor/orders.$orderId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotDealsRoute = HotDealsRouteImport.update({
  id: '/hot-deals',
  path: '/hot-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashDealsRoute = FlashDealsRouteImport.update({
  id: '/flash-deals',
  path: '/flash-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/vendor/products',
  path: '/vendor/products',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorApplicationRejectedRoute =
  VendorApplicationRejectedRouteImport.update({
    id: '/vendor/application-rejected',
    path: '/vendor/application-rejected',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorApplicationPendingRoute =
  VendorApplicationPendingRouteImport.update({
    id: '/vendor/application-pending',
    path: '/vendor/application-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackOrderNumberRoute = TrackOrderNumberRouteImport.update({
  id: '/track/$orderNumber',
  path: '/track/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSlugRoute = ProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorApplicationsRoute = AdminVendorApplicationsRouteImport.update({
  id: '/admin/vendor-applications',
  path: '/admin/vendor-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersOrderIdRoute = VendorOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/flash-deals': typeof FlashDealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hot-deals': typeof HotDealsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendor-applications': typeof AdminVendorApplicationsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/vendor/application-pending': typeof VendorApplicationPendingRoute
  '/vendor/application-rejected': typeof VendorApplicationRejectedRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/flash-deals': typeof FlashDealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hot-deals': typeof HotDealsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendor-applications': typeof AdminVendorApplicationsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/vendor/application-pending': typeof VendorApplicationPendingRoute
  '/vendor/application-rejected': typeof VendorApplicationRejectedRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/flash-deals': typeof FlashDealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hot-deals': typeof HotDealsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendor-applications': typeof AdminVendorApplicationsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/track/$orderNumber': typeof TrackOrderNumberRoute
  '/vendor/application-pending': typeof VendorApplicationPendingRoute
  '/vendor/application-rejected': typeof VendorApplicationRejectedRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/addresses'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/flash-deals'
    | '/forgot-password'
    | '/hot-deals'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendor-applications'
    | '/admin/vendors'
    | '/category/$categorySlug'
    | '/product/$productSlug'
    | '/track/$orderNumber'
    | '/vendor/application-pending'
    | '/vendor/application-rejected'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account/orders/$orderId'
    | '/vendor/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/addresses'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/flash-deals'
    | '/forgot-password'
    | '/hot-deals'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendor-applications'
    | '/admin/vendors'
    | '/category/$categorySlug'
    | '/product/$productSlug'
    | '/track/$orderNumber'
    | '/vendor/application-pending'
    | '/vendor/application-rejected'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account/orders/$orderId'
    | '/vendor/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/addresses'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/flash-deals'
    | '/forgot-password'
    | '/hot-deals'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vendor-applications'
    | '/admin/vendors'
    | '/category/$categorySlug'
    | '/product/$productSlug'
    | '/track/$orderNumber'
    | '/vendor/application-pending'
    | '/vendor/application-rejected'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account/orders/$orderId'
    | '/vendor/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AddressesRoute: typeof AddressesRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FlashDealsRoute: typeof FlashDealsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HotDealsRoute: typeof HotDealsRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WishlistRoute: typeof WishlistRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorApplicationsRoute: typeof AdminVendorApplicationsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  ProductProductSlugRoute: typeof ProductProductSlugRoute
  TrackOrderNumberRoute: typeof TrackOrderNumberRoute
  VendorApplicationPendingRoute: typeof VendorApplicationPendingRoute
  VendorApplicationRejectedRoute: typeof VendorApplicationRejectedRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorOrdersRoute: typeof VendorOrdersRouteWithChildren
  VendorProductsRoute: typeof VendorProductsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-deals': {
      id: '/hot-deals'
      path: '/hot-deals'
      fullPath: '/hot-deals'
      preLoaderRoute: typeof HotDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-deals': {
      id: '/flash-deals'
      path: '/flash-deals'
      fullPath: '/flash-deals'
      preLoaderRoute: typeof FlashDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/application-rejected': {
      id: '/vendor/application-rejected'
      path: '/vendor/application-rejected'
      fullPath: '/vendor/application-rejected'
      preLoaderRoute: typeof VendorApplicationRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/application-pending': {
      id: '/vendor/application-pending'
      path: '/vendor/application-pending'
      fullPath: '/vendor/application-pending'
      preLoaderRoute: typeof VendorApplicationPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderNumber': {
      id: '/track/$orderNumber'
      path: '/track/$orderNumber'
      fullPath: '/track/$orderNumber'
      preLoaderRoute: typeof TrackOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSlug': {
      id: '/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof ProductProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendor-applications': {
      id: '/admin/vendor-applications'
      path: '/admin/vendor-applications'
      fullPath: '/admin/vendor-applications'
      preLoaderRoute: typeof AdminVendorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders/$orderId': {
      id: '/vendor/orders/$orderId'
      path: '/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof VendorOrdersOrderIdRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface VendorOrdersRouteChildren {
  VendorOrdersOrderIdRoute: typeof VendorOrdersOrderIdRoute
}

const VendorOrdersRouteChildren: VendorOrdersRouteChildren = {
  VendorOrdersOrderIdRoute: VendorOrdersOrderIdRoute,
}

const VendorOrdersRouteWithChildren = VendorOrdersRoute._addFileChildren(
  VendorOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AddressesRoute: AddressesRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FlashDealsRoute: FlashDealsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HotDealsRoute: HotDealsRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WishlistRoute: WishlistRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorApplicationsRoute: AdminVendorApplicationsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  ProductProductSlugRoute: ProductProductSlugRoute,
  TrackOrderNumberRoute: TrackOrderNumberRoute,
  VendorApplicationPendingRoute: VendorApplicationPendingRoute,
  VendorApplicationRejectedRoute: VendorApplicationRejectedRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorOrdersRoute: VendorOrdersRouteWithChildren,
  VendorProductsRoute: VendorProductsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
